name: legal_doc_scanner
description: A Flutter app to scan and summarize legal documents

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^8.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
